name: ClusterFuzzLite PR Scanning

on:
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        language: python # Change to your language: c++, go, rust, java, etc.
    - name: Run Fuzzers
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 600
        mode: 'pr'
